/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MessApp;

import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Anshuman-HP
 */
public class ListFrame extends javax.swing.JFrame  {

    /**
     * Creates new form ListFrame
     * 
     * 
     */
    int numOfVeg=0;
    int numOfNonVegPlate=0;
    String message;
    public ListFrame() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();
        getList = new javax.swing.JButton();
        Print = new javax.swing.JButton();
        InfoMessage = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "SlNo.", "Name", "Mobile Number", "Address", "Amount", "Remarks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listTable);

        getList.setText("GetList");
        getList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getListActionPerformed(evt);
            }
        });

        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(getList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Print)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InfoMessage)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getList)
                    .addComponent(Print))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoMessage)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        try {
            // TODO add your handling code here:
            // TODO add header and footer
            //listTable.print();
            MessageFormat format=new MessageFormat(InfoMessage.getText());
            listTable.print(JTable.PrintMode.FIT_WIDTH,format,null);
        } catch (PrinterException ex) {
            Logger.getLogger(ListFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrintActionPerformed

    private void getListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getListActionPerformed

                // TODO add your handling code here:
                numOfNonVegPlate=0;
                numOfVeg=0;
                String date;
                String[] dayChoices = { "Today", "Tommorow" };
                String dayInput = (String) JOptionPane.showInputDialog(null, "Choose ","For", JOptionPane.QUESTION_MESSAGE, null,dayChoices,dayChoices[1]);
                System.out.println(dayInput);
                java.sql.Timestamp dateInput;
                if(dayInput.equals("Today")){
                    Calendar cal=Calendar.getInstance();
                    dateInput=new java.sql.Timestamp(cal.getTime().getTime());
                    date = new SimpleDateFormat("YYYY-MM-dd hh:mm:ss").format(dateInput);

                   
                }
                else {
                    Calendar cal=Calendar.getInstance();
                    cal.add(Calendar.DAY_OF_YEAR, 1);
                    dateInput=new java.sql.Timestamp(cal.getTime().getTime());
                    date = new SimpleDateFormat("YYYY-MM-dd hh:mm:ss").format(dateInput);

                }
                
                
                String[] mealTypeChoices = { "breakfast", "lunch", "dinner" };
                String mealInput = (String) JOptionPane.showInputDialog(null, "Choose ","Meal Type", JOptionPane.QUESTION_MESSAGE, null,mealTypeChoices,mealTypeChoices[1]);
                System.out.println(mealInput);
                System.out.println(dateInput);
                
                try {
                    String finalQuery="SELECT * from customerdetails LEFT JOIN cancel "+
                            " ON (customerdetails.name=cancel.name AND customerdetails.address=cancel.address) "+
                            " WHERE (((customerdetails."+mealInput+
                            " AND (cancel.name IS NULL)) "+
                            " OR(((customerdetails."+mealInput+" AND (NOT (cancel.stop) AND NOT(cancel.restart)))"+
                            " AND ((NOT cancel."+mealInput+
                            " )OR((cancel."+mealInput+")"+
                            " AND NOT (#"+date+"#"+
                            " between (cancel.fromdate) AND (cancel.todate))))))))"+
                            " order by SerialNumber";
                            
                   
                    System.out.println(finalQuery);
                    ResultSet listSet=MainFrame.DBconn.createStatement().executeQuery(finalQuery);
                    DefaultTableModel model = (DefaultTableModel) listTable.getModel();
                    model.setNumRows(0);
                    System.out.println(finalQuery);
                    int n=1;
                    while(listSet.next()){
                        Vector row = new Vector();
                        System.out.println(listSet.getString("name"));
                        row.add(n);
                        row.add(listSet.getString("name"));
                        row.add(listSet.getLong("mobilenumber"));
                        row.add(listSet.getString("address"));
                        row.add(listSet.getInt("Amount"));
                        row.add(listSet.getString("Remarks"));
                        if(listSet.getBoolean("Veg")){
                            numOfVeg++;
                        }else{
                            if(listSet.getBoolean("Full")){
                                numOfNonVegPlate=numOfNonVegPlate+2;
                            }
                            else{
                                numOfNonVegPlate++;
                            }
                        }
                        model.addRow(row);
                        n++;
                    }
                    
                    String stopQuery="SELECT * from customerdetails LEFT JOIN cancel ON (customerdetails.name=cancel.name AND customerdetails.address=cancel.address) WHERE(((cancel.stop AND NOT(cancel.restart)) AND customerdetails."+mealInput+") AND ((NOT cancel."+mealInput+") AND (#"+date+"# <= cancel.fromdate)))";
                    
                    ResultSet stoplistSet=MainFrame.DBconn.createStatement().executeQuery(stopQuery);
                    System.out.println(stopQuery);

                    while(stoplistSet.next()){
                        Vector row = new Vector();
                        System.out.println("name"+stoplistSet.getString("name"));
                        row.add(n);
                        row.add(stoplistSet.getString("name"));
                        row.add(stoplistSet.getLong("mobilenumber"));
                        row.add(stoplistSet.getString("address"));
                        row.add(stoplistSet.getInt("Amount"));
                        row.add(stoplistSet.getString("Remarks"));
                        if(stoplistSet.getBoolean("Veg")){
                            numOfVeg++;
                        }else{
                            if(stoplistSet.getBoolean("Full")){
                                numOfNonVegPlate=numOfNonVegPlate+2;
                            }
                            else{
                                numOfNonVegPlate++;
                            }
                        }
                        model.addRow(row);
                        n++;
                    }
                    String restartQuery="SELECT * from customerdetails LEFT JOIN cancel ON (customerdetails.name=cancel.name AND customerdetails.address=cancel.address) WHERE(((cancel.restart AND NOT(cancel.stop)) AND customerdetails."+mealInput+") AND ((NOT cancel."+mealInput+") AND (#"+date+"# <= cancel.fromdate)))";
                    
                    ResultSet restartlistSet=MainFrame.DBconn.createStatement().executeQuery(restartQuery);
                    System.out.println(stopQuery);

                    while(stoplistSet.next()){
                        Vector row = new Vector();
                        System.out.println("name"+stoplistSet.getString("name"));
                        row.add(n);
                        row.add(stoplistSet.getString("name"));
                        row.add(stoplistSet.getLong("mobilenumber"));
                        row.add(stoplistSet.getString("address"));
                        row.add(stoplistSet.getInt("Amount"));
                        row.add(stoplistSet.getString("Remarks"));
                        if(stoplistSet.getBoolean("Veg")){
                            numOfVeg++;
                        }else{
                            if(stoplistSet.getBoolean("Full")){
                                numOfNonVegPlate=numOfNonVegPlate+2;
                            }
                            else{
                                numOfNonVegPlate++;
                            }
                        }
                        model.addRow(row);
                        n++;
                    }
                } catch (SQLException ex) {
                    
                    Logger.getLogger(ListFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
               message="For "+dateInput+"  ("+mealInput+") Veg-"+numOfVeg+" Non-Veg-"+numOfNonVegPlate;
               InfoMessage.setText(message);
    }//GEN-LAST:event_getListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InfoMessage;
    private javax.swing.JButton Print;
    private javax.swing.JButton getList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable listTable;
    // End of variables declaration//GEN-END:variables
}
